backend:
    name: git-gateway

media_folder: "static/images"
public_folder: "/images"

collections:
  - name: "posts"
    label: "Posts"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Introduction", name: "introduction", widget: "string", hint: "Introductions are only shown on the overview."}
      - {label: "Preview image", name: "image", widget: "image"}
      - {label: "Publish Date", name: "date", widget: "date"}
      - {label: "Save as draft", name: "isDraft", widget: "boolean", default: true, hint: "Draft publications are hidden from visitors."}
      - {label: "Body", name: "content", widget: "markdown"}
  - name: "generalPages"
    label: "Pages"
    files:
      - label: "Workshops"
        name: "workshops"
        file: "content/pages/workshops.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "content", widget: "markdown"}
      - label: "About"
        name: "about"
        file: "content/pages/about.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "content", widget: "markdown"}
